### PR TITLE
functions for estimating difference between dates that are in string format initiated

### PR DESCRIPTION
**Pull request by kcho**
Functions to be used in creating the new dataflow view in DPdash.

### CODE REVIEW

**Comment by kcho** [comment]
Added functions to extract GUID for a given AMP-SCZ ID

**Comment by tashrifbillah** [comment]
> Added functions to extract GUID for a given AMP-SCZ ID

https://gist.github.com/tashrifbillah/db7ef28d29429a2d2df8991a8540a014

**Comment by kcho** [comment]
Initialized functions to extract a single QC variable from the MRI run sheet.

**Comment by tashrifbillah** [comment]
I plan to use many functions from Kevin's `util.py`.

**Comment by tashrifbillah** [comment]
Kevin's work is a good starting point for revising our DPdash aggregate data flow. His work is separate from other functions. So I am merging it. Kevin is probably already using his work to render one such view in DPdash.

**Comment by tashrifbillah** [comment]
Deployed on `/data/predict1/` .

**Pull request merged**
